"""Add blocks table for user blocking

Revision ID: b71510aa6831
Revises: 27499cd3fe79
Create Date: 2025-10-16 11:03:40.481376

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b71510aa6831'
down_revision = '27499cd3fe79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Department')
    op.drop_table('School')
    op.drop_table('Post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post',
    sa.Column('post_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('scope', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name=op.f('Post_user_id_fkey')),
    sa.PrimaryKeyConstraint('post_id', name=op.f('Post_pkey'))
    )
    op.create_table('School',
    sa.Column('school_id', sa.INTEGER(), server_default=sa.text('nextval(\'"School_school_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('school_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('school_id', name='School_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Department',
    sa.Column('department_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('department_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['School.school_id'], name=op.f('Department_school_id_fkey')),
    sa.PrimaryKeyConstraint('department_id', name=op.f('Department_pkey'))
    )
    # ### end Alembic commands ###
