"""Add gomoku_score to User

Revision ID: eaa306c01d76
Revises: 7b16d6b88293
Create Date: 2025-11-13 09:51:05.924780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaa306c01d76'
down_revision = '7b16d6b88293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gomoku_score', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('gomoku_score')

    # ### end Alembic commands ###
